apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1app1nginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1app1nginxaks
  template:
    metadata:
      labels:
        app: app1app1nginxaks 
    spec:
      containers:
        - name: app1app1nginxaks 
          image: asazanowiczazuredevopsgithubacraksapp1.azurecr.io/app1app1nginxaks
          ports:
          - containerPort: 80